version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: aiffinity_db
      MYSQL_USER: user
      MYSQL_PASSWORD: MyPassword
      MYSQL_ROOT_PASSWORD: MyRootPassword
    ports:
      - '5306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - aiffinity_network

  # backend:
  #   build: ./backend
  #   ports:
  #     - '6000:6000'
  #   environment:
  #     - DB_NAME=aiffinity_db
  #     - DB_USER=user
  #     - DB_PASSWORD=<MyPassword>
  #     - DB_HOST=db
  #     - JWT_SECRET=tu_secreto_jwt
  #     - OPENAI_API_KEY=tu_api_key_openai
  #   depends_on:
  #     - db
  #   networks:
  #     - aiffinity_network

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '4020:4020'
  #   environment:
  #     - NEXTAUTH_SECRET=tu_secreto_nextauth
  #   depends_on:
  #     - backend
  #   networks:
  #     - aiffinity_network

networks:
  aiffinity_network:
    driver: bridge

volumes:
  db_data:
