version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aiffinity_db
      MYSQL_USER: user
      MYSQL_PASSWORD: MyPassword_aiffinity
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-MyRootPassword_aiffinity}
      TZ: Europe/Madrid
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD} -h localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [aiffinity_network]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks: [aiffinity_network]

  backend:
    build:
      context: ./backend
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: MyPassword_aiffinity
      DB_NAME: aiffinity_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: tu_secreto_jwt
      OPENAI_API_KEY: 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
      CLOUDINARY_CLOUD_NAME: dlutrgfri
      CLOUDINARY_API_KEY: 516379456761389
      CLOUDINARY_API_SECRET: qJ06Vkue-VSPnFwqpAco5WN0T60
    ports:
      - "2159:2159"
    restart: unless-stopped
    networks: [aiffinity_network]

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports: ["3000:3000"]
    restart: unless-stopped
    networks: [aiffinity_network]

networks:
  aiffinity_network:
    driver: bridge

volumes:
  db_data:
