# backend/Dockerfile

# BUILD
FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

# RUNTIME
FROM node:20-slim

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app /app

USER node

EXPOSE 2159

CMD ["npm", "start"]

